repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: check-json
    -   id: fix-byte-order-marker

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
    -   id: remove-crlf
    -   id: forbid-tabs
        exclude: (Makefile|\.mk|go\.mod|go\.sum|\.gitmodules)


# Local Emacs hooks using Emacs in batch mode
-   repo: local
    hooks:
    -   id: checkdoc
        name: Emacs Checkdoc
        entry: >
          emacs --batch -Q --eval '(setq checkdoc-create-error-function (lambda (text start end &optional unfixable) (error text)))'
          -l checkdoc -f checkdoc-current-buffer
        language: system
        files: '\.el$'
        exclude: '\.dir-locals\.el$'

    -   id: package-lint
        name: Emacs Package-Lint
        entry: emacs --batch -Q --eval "(progn
                (require 'package)
                (add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\") t)
                (package-initialize)
                (unless (package-installed-p 'package-lint)
                  (package-refresh-contents)
                  (package-install 'package-lint))
                (require 'package-lint))"
                -f package-lint-batch-and-exit
        language: system
        files: '\.el$'
        exclude: '\.dir-locals\.el$'

    -   id: indent-elisp
        name: Format Emacs Lisp
        language: system
        entry: >
          emacs --batch -Q --eval '(progn
          (setq indent-tabs-mode nil)
          (find-file (car command-line-args-left))
          (indent-region (point-min) (point-max))
          (untabify (point-min) (point-max))
          (save-buffer))'
        files: '\.el$'
        exclude: '\.dir-locals\.el$'
